### PR TITLE
accept strings in constructor

### PR DESCRIPTION
**Pull request by MaxBittker**
this will look for string-like inputs, and parse them correctly into patch sets, allowing the syntax in 
https://github.com/matiasb/python-unidiff/issues/26

I'm happy to update examples/tests or otherwise improve this if you feel iffy about the implementation or behavior.👍

### CODE REVIEW

**Comment by MaxBittker** [comment]
@matiasb hey there, there's no rush acting on this but I wanted to bring it to your attention in case it slipped through 👍

**Comment by matiasb** [comment]
In my queue! I'll be taking a look soon.
Thanks for the quick patch :+1:

**Comment by MaxBittker** [comment]
awesome, thanks. not high priority but I don't want to forget about it and I think it's helpful

**Comment by matiasb** [comment]
I'm still not convinced the __init__ should guess the type before parsing, given there is an explicit classmethod for strings. In that way, it is responsibility of the caller to decide which constructor to use (and for example, if there is something that should be treated as string but it is not a string, he/she could make the decision instead of us guessing it wrong).

I'm merging the change, codewise looks good, but I think it may mutate before a next release. Thanks!

**Pull request merged**
