### PR TITLE
support binary patch format

### PR DESCRIPTION
**Pull request by marxin**
Fixes: #105

### CODE REVIEW

**Comment by marxin** [comment]
May I please ping this @matiasb?

**Comment by matiasb** [comment]
Thanks for the PR! :+1: 

Sorry for the delay in the answer, it's been a busy EOY and I'm still catching up with a few things. Will be reviewing some stuff and preparing a release soon.

**Comment by marxin** [comment]
Thanks, looking forward to the release.

**Comment by marxin** [comment]
May I please remind you to do a new release? Thanks.

**Pull request merged**
